title: "Dani Boj"
email: dani@dboj-sol.nom.es
description: >- # this means to ignore newlines until "baseurl:"
  Welcome, here you will find some of my work as a Sysadmin!
baseurl: "/" 
url: "https://portfolio.dboj-sol.nom.es/"
# You only need to define your social links here and no need to edit the footer.html
social:
  #twitter_username: wrussell1999
  github_username:  DanielBoj
  linkedin_username: dani-boj


sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
resume: /assets/resume.pdf
